### ISSUE TITLE
Jenkins setup question

### ISSUE THREAD

**Issue by akamalov** [mrbobbytables/jenkins#5]
Hey Bob,

Thanks so much for the awesome repo.  I am planning building Jenkins based on your repo, however I had a question: Is this image supposed to spawn up Mesos slaves on-demand on Jenkins-Slaves, based on Docker image ? I noticed this: JENKINS_MESOS_SLAVE_2_DOCK_IMG. What if I do not want Mesos-Slave to be deployed, but Jenkins Slaves only?

Thanks so much for your answer in advance!!

Thanks

**Comment by mrbobbytables** [comment]
The Jenkins mesos framework itself is meant to spin up on-demand jenkins build slave containers within a pre-existing mesos cluster. It does not act as a mesos-slave itself -- Note, if the mesos-slave is running in a container, it will require some modification (jenkins user/group added -- see [mrbobbytables/mesos-slave-jenkins](https://github.com/mrbobbytables/mesos-slave-jenkins)). 

The jenkins mesos plugin provides the ability to define multiple jenkins build slaves -- e.g. you may have one for executing building/testing of php apps and another for nodejs. This is where the `JENKINS_MESOS_SLAVE_<###>_<variable>` env variables come in. All variables with the same `###` will be associated together as a part of a single slave definition. The [jenkins section of the readme](https://github.com/mrbobbytables/jenkins#jenkins) covers this in a bit more detail.

If you want to quickly see it in action, [TheGrid](https://github.com/mrbobbytables/thegrid) project I have is a bit of a tutorial with a mesos stack similar to what we run. You can see what the jenkins-mesos plugin looks like and how it behaves.

Hope that helps!

**Comment by akamalov** [comment]
Thanks so much, Bob. That clarifies a lot.

Thanks again,

Alex
